### ISSUE TITLE
Evaluation of Generated Music

### ISSUE THREAD

**Issue by amtrivedi91** [MattVitelli/GRUV#4]
How do you guys think that the generated music should be evaluated? Are you using a measure to quantify the generated sequences that labels them "good" or "bad" or does one have to actually listen to the songs to judge? Also, can you please clear up on what basis you found that LSTMs were better than GRUs?

**Comment by amtrivedi91** [comment]
Would it make sense if we tried to see whether some existing models classify the generated output as HIT? See for eg. this [App](http://scoreahit.com) - ([Paper](http://www.tijldebie.net/system/files/MML2011-final.pdf)).

**Comment by anayebi** [comment]
We generally just evaluated it by listening to it. If it sounded very noisy with hardly any audible sound, then we would discard it. This was often the case with GRUs, and that's how we found that LSTMs were better as they consistently gave audibly plausible outputs (the summary on pg. 6 of our paper states this), please see the paper for more details: http://cs224d.stanford.edu/reports/NayebiAran.pdf.

You're more than welcome to try out some existing models to classify generated music sequences. I think the paper you reference is more for determining if a song is a hit song, rather than it merely being audibly/musically plausible (we stuck to the latter criterion since even with the LSTM's output, there was noise, so I imagine something that classifies hit songs well would not like the fact that there is static in it regardless of whether the underlying signal with noise removed would be a hit song or not). But again, you're welcome to try it and see what happens!

**Comment by amtrivedi91** [comment]
Thanks for your quick reply.

I am doing something similar for a college project of mine, but I think it would be better to have some sort of an 'output evaluator' in place other than just listening to the music.

I (& my partner) are new to this and are trying to understand things as fast as we can, but we still haven't figured out what the best way to do evaluation would be, do you have any ideas?

Or maybe you come across some paper which did evaluation, because we have seen some sequence generation papers and none of them evaluated their output.

**Comment by mattvitellioculus** [comment]
There are a few ways you can come up with quantitative metrics for how well your generation scheme is performing. The easiest to implement metric would be the L2 error between your generated sequence and a ground-truth sequence, where you use the first N samples of the ground-truth sequence as an input to your generation algorithm. If you're doing MIDI music generation or have some concept of notes and chords, you'll probably want to use a different distance metric, such as hamming or edit distance between the two sequences.

We didn't evaluate the generation algorithms quantitatively in our paper, because our network is essentially learning the generation metric I mentioned up above, so you'd expect the generation error to be equivalent to the dev error.

**Comment by MattVitelli** [comment]
There are a few ways you can come up with quantitative metrics for how well your generation scheme is performing. The easiest to implement metric would be the L2 error between your generated sequence and a ground-truth sequence, where you use the first N samples of the ground-truth sequence as an input to your generation algorithm. If you're doing MIDI music generation or have some concept of notes and chords, you'll probably want to use a different distance metric, such as hamming or edit distance between the two sequences.

We didn't evaluate the generation algorithms quantitatively in our paper, because our network is essentially learning the generation metric I mentioned up above, so you'd expect the generation error to be equivalent to the dev error.
